version: '3.8'

services:
  hr-portal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://mukesh:mukesh%40vis123@db.vis.com.pk:3306/vis_company
      - NEXTAUTH_SECRET=bda4f27e2e67a7c4a5d93e0f9e3b8b8e3dca9f6279f93baf237cd8769d3a9123
      - NEXTAUTH_URL=http://localhost:3000
      - LOCALHOST_SERVER=http://localhost:3000
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - hr-network

  # Optional: Include MySQL database service if you want to run it locally
  # Remove this section if you're using external database
  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=vis_company
      - MYSQL_USER=mukesh
      - MYSQL_PASSWORD=mukesh@vis123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hr-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  hr-network:
    driver: bridge